/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SkillInference': EventHandler<{ developerId: string; date: string }, never>
    'ProcessEvents': EventHandler<{ batchId: string; events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; timestamp: number }, never>
    'DailyAggregation': CronHandler<{ topic: 'infer-skills'; data: { developerId: string; date: string } }>
    'DeveloperInsights': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; developerId: string }>, never>
    'Health': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string; service: string }>, never>
    'EventsIngestion': ApiRouteHandler<{ events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; batchId: string; timestamp: number }, ApiResponse<200, { success: boolean; message: string; batchId: string; processedCount: number }> | ApiResponse<400, { success: boolean; message: string; error?: string }> | ApiResponse<429, { success: boolean; message: string; error?: string }> | ApiResponse<500, { success: boolean; message: string; error?: string }>, { topic: 'process-events'; data: { batchId: string; events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; timestamp: number } }>
  }
    
}