/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SkillInference': EventHandler<{ developerId: string; date: string }, never>
    'ProcessEvents': EventHandler<{ batchId: string; events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; timestamp: number }, never>
    'PrivacyControlHandler': EventHandler<never, never>
    'DataRetentionCleanup': CronHandler<never>
    'DailyAggregation': CronHandler<{ topic: 'infer-skills'; data: { developerId: string; date: string } }>
    'DeveloperInsights': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { developerId: string; generatedAt: string; insights: Array<{ metric: string; currentValue: string; trend: 'improving' | 'stable' | 'declining'; trendDescription: string; explanation: string; confidenceLevel: 'high' | 'medium' | 'low' }>; summary: { overallTrend: 'improving' | 'stable' | 'declining'; keyStrengths: Array<string>; areasForImprovement: Array<string>; trendExplanation: string }; privacyNote: string } | unknown; message: string }>, never>
    'DeveloperTrends': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { developerId: string; generatedAt: string; insights: Array<{ metric: string; currentValue: string; trend: 'improving' | 'stable' | 'declining'; trendDescription: string; explanation: string; confidenceLevel: 'high' | 'medium' | 'low' }>; summary: { overallTrend: 'improving' | 'stable' | 'declining'; keyStrengths: Array<string>; areasForImprovement: Array<string>; trendExplanation: string }; privacyNote: string } | unknown; message: string }>, never>
    'InsightsPause': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; developerId: string; action: 'pause' | 'resume'; timestamp: string }>, { topic: 'privacy-control-changed'; data: never }>
    'Health': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string; service: string }>, never>
    'EventsIngestion': ApiRouteHandler<{ events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; batchId: string; timestamp: number }, ApiResponse<200, { success: boolean; message: string; batchId: string; processedCount: number }> | ApiResponse<400, { success: boolean; message: string; error?: string }> | ApiResponse<429, { success: boolean; message: string; error?: string }> | ApiResponse<500, { success: boolean; message: string; error?: string }>, { topic: 'process-events'; data: { batchId: string; events: Array<{ id: string; developerId: string; timestamp: number; eventType: 'keystroke_burst' | 'paste' | 'ai_invocation' | 'debug_action' | 'file_switch' | 'error_marker'; metadata: { burstDuration?: number; characterCount?: number; pasteLength?: number; timeSinceAiInvocation?: number; toolType?: 'copilot' | 'chat' | 'other'; invocationContext?: 'coding' | 'debugging' | 'documentation'; actionType?: 'run' | 'debug' | 'test'; errorCount?: number; fileExtension?: string; switchFrequency?: number; errorAppeared?: boolean; errorResolved?: boolean; timeToResolve?: number }; sessionId: string }>; timestamp: number } }>
    'DataRetentionReport': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; data: { currentStats: { totalEvents: number; processedEvents: number; unprocessedEvents: number; dailyMetrics: number; skillAssessments: number; oldestEventDate: string | unknown; newestEventDate: string | unknown }; retentionPolicy: { name: string; description: string; eventsRetentionDays: number; metricsRetentionDays: number; assessmentsRetentionDays: number; maxStorageSizeMB: number; cleanupBatchSize: number }; recommendations: Array<string> }; message: string }>, never>
  }
    
}